# =============================================================================
# SSH KEY PAIR CONFIGURATION
# =============================================================================
# This file creates an SSH key pair for secure access to EC2 instances.
# The private key is generated by Terraform and stored in the state file.
# The public key is uploaded to AWS as a key pair resource.

# Generate a private key using the TLS provider
# This creates a new RSA private key that will be used for SSH authentication
resource "tls_private_key" "shah_private_key" {
  # Use RSA algorithm for the key pair
  # RSA is widely supported and compatible with most SSH clients
  algorithm = "RSA"
  
  # Set key size to 4096 bits for enhanced security
  # 4096-bit keys provide stronger encryption than the default 2048-bit keys
  # This is recommended for production environments
  rsa_bits = 4096
}

# Create an AWS key pair using the generated public key
# This uploads the public key to AWS so it can be associated with EC2 instances
resource "aws_key_pair" "shah_key_pair" {
  # Name for the key pair in AWS
  # This name will be used when launching EC2 instances
  key_name = "shah-key"
  
  # Use the public key from the generated private key
  # The public_key_openssh format is compatible with AWS key pairs
  # This creates the association between the local private key and AWS public key
  public_key = tls_private_key.shah_private_key.public_key_openssh
}